export const OBJECTS = [
  {
    id: 'smartphone',
    name: 'Smartphone',
    aliases: ['phone', 'smart phone', 'smartphone device', 'smart mobile', 'mobile phone', 'mobile telephone', 'mobile', 'cell phone', 'cellphone', 'cellular phone', 'cellular telephone', 'handset', 'smart handset', 'mobile device', 'touchscreen phone', 'touch phone', 'iphone', 'apple iphone', 'android phone', 'android mobile', 'samsung galaxy phone', 'galaxy phone', 'google pixel', 'pixel phone'],
    category: 'Personal tech',
    descriptor: 'Everyday technology',
    portable: true,
    powered: true,
    setting: 'personal use',
    finishedPrice: {
      range: '$100–$2,300 per unit',
      basis: 'Typical new retail price, before carrier plans, trade-ins or accessories.',
      tiers: [['Budget', '$100–$300'], ['Mainstream', '$300–$900'], ['Premium', '$900–$1,500'], ['Specialty', '$1,500–$2,300']],
    },
    guessMaterials: ['Copper', 'Cobalt', 'Lithium', 'Silicon', 'Rare earths'],
    materials: [
      ['Glass & ceramics', 55, 0.80], ['Aluminum', 22.18, 3.254], ['Electrolyte & binders', 16.2796, 10],
      ['Copper', 15.12, 14.74], ['Graphite', 10, 0.32], ['Plastics', 9.53, 1.50], ['Magnesium', 5.54, 3.50],
      ['Cobalt', 5.38, 39.14], ['Nickel', 4.50, 16.05], ['Epoxy & resins', 4, 5], ['Silicon', 3, 2.50],
      ['Adhesives & coatings', 3, 8], ['Lithium compounds', 2, 17.51], ['Manganese', 1.50, 2], ['Tin', 1.21, 54.20],
      ['Steel / iron', 0.88, 0.80], ['Tungsten', 0.44, 153.46], ['Silver', 0.31, 1951.50],
      ['Neodymium', 0.05, 154.85], ['Gold', 0.03, 133800], ['Tantalum', 0.02, 535],
      ['Praseodymium', 0.01, 130], ['Indium', 0.01, 350], ['Palladium', 0.01, 52000], ['Gallium', 0.0004, 400],
    ],
    stages: {
      components: [
        ['China', 30, null, ['Display modules', 'battery packs', 'circuit boards'], '156'],
        ['Taiwan', 16, null, ['Semiconductor fabrication', 'processor packages'], '158'],
        ['South Korea', 14, null, ['Memory chips', 'displays', 'battery cells'], '410'],
        ['Japan', 11, null, ['Image sensors', 'camera modules', 'electronic materials'], '392'],
        ['Vietnam', 7, null, ['Camera modules', 'electronic subassemblies'], '704'],
        ['Malaysia', 5, null, ['Chip packaging and testing', 'passive components'], '458'],
        ['Singapore', 4, null, ['Semiconductor fabrication', 'storage components'], null],
        ['United States', 4, null, ['Specialty chips', 'radio-frequency components'], '840'],
        ['Germany', 2, null, ['Sensors', 'power semiconductors'], '276'],
        ['Philippines', 2, null, ['Chip assembly and testing', 'passive components'], '608'],
        ['Thailand', 1.5, null, ['Circuit boards', 'electronic subassemblies'], '764'],
        ['Mexico', 1.5, null, ['Circuit boards', 'cable assemblies'], '484'],
        ['Other', 2, null, ['Connectors', 'speakers', 'minor modules'], null],
      ],
      assembly: [['China', 45], ['Vietnam', 14], ['India', 11], ['South Korea', 7], ['Brazil', 3], ['Indonesia', 3], ['Mexico', 2], ['Turkey', 2], ['Egypt', 1.5], ['Pakistan', 1.5], ['Bangladesh', 1], ['Japan', 1], ['Taiwan', 1], ['Other', 7]],
      buyers: [['United States', 18], ['China', 15], ['India', 9], ['Germany', 5], ['Japan', 4.5], ['United Kingdom', 4], ['Brazil', 3.5], ['Indonesia', 3.5], ['France', 3], ['Mexico', 3], ['Thailand', 3], ['Italy', 2.5], ['Spain', 2.5], ['South Korea', 2.5], ['Canada', 2.5], ['Russia', 2], ['Turkey', 2], ['Saudi Arabia', 2], ['Australia', 1.5], ['United Arab Emirates', 1.5], ['Netherlands', 1.5], ['Nigeria', 1], ['South Africa', 1], ['Argentina', 1], ['Poland', 1], ['Other', 4]],
      sources: [['China', 24, null, ['Graphite', 'rare earths', 'tungsten', 'gallium']], ['DR Congo', 18, null, ['Cobalt', 'copper', 'tantalum']], ['Australia', 11, null, ['Lithium', 'nickel', 'gold']], ['Chile', 8, null, ['Copper', 'lithium']], ['Peru', 6, null, ['Copper', 'silver', 'tin']], ['Indonesia', 6, null, ['Nickel', 'tin']], ['Russia', 4, null, ['Nickel', 'palladium']], ['Brazil', 4, null, ['Tantalum', 'tin', 'graphite']], ['Rwanda', 3, null, ['Tantalum', 'tungsten', 'tin']], ['Argentina', 3, null, ['Lithium', 'copper']], ['Philippines', 2, null, ['Nickel', 'copper']], ['South Africa', 2, null, ['Manganese', 'palladium']], ['Canada', 2, null, ['Nickel', 'cobalt', 'gold']], ['United States', 2, null, ['Copper', 'lithium', 'rare earths']], ['Other', 5, null, ['Silicon', 'aluminum ores', 'specialty metals']]],
      logistics: [['Hong Kong', 20], ['United Arab Emirates', 17], ['Netherlands', 11], ['Singapore', 10], ['Czechia', 7], ['Slovakia', 5], ['Belgium', 5], ['Germany', 5], ['Panama', 4], ['Malaysia', 4], ['Poland', 3], ['Turkey', 3], ['Mexico', 2], ['Saudi Arabia', 2], ['Other', 2]],
      waste: [['China', 19.5], ['United States', 12], ['India', 9], ['Japan', 5], ['Brazil', 4], ['Indonesia', 4], ['Russia', 4], ['Germany', 3.5], ['United Kingdom', 3], ['France', 3], ['Mexico', 3], ['Turkey', 2.5], ['South Korea', 2.5], ['Italy', 2.5], ['Nigeria', 2], ['Pakistan', 2], ['Vietnam', 2], ['Thailand', 2], ['Spain', 2], ['Poland', 1.5], ['Canada', 1.5], ['Australia', 1.5], ['Ghana', 1.5], ['South Africa', 1.5], ['United Arab Emirates', 1], ['Other', 4]],
    },
    feedback: [
      'It is made to travel with one person, not stay in one room.',
      'Its battery stores energy in lithium compounds and may contain cobalt.',
      'Its most valuable parts are tiny chips, even though glass and metals dominate its weight.',
      'It connects to cellular networks and usually has a touchscreen.',
    ],
    mapRoles: {
      '180': ['source'], '036': ['source', 'buyer', 'waste'], '152': ['source'], '604': ['source'],
      '643': ['source', 'buyer', 'waste'], '646': ['source'], '032': ['source', 'buyer'], '608': ['source'],
      '710': ['source', 'buyer', 'waste'], '124': ['source', 'buyer', 'waste'], '840': ['source', 'buyer', 'waste'],
      '158': ['assembly'], '392': ['assembly', 'buyer', 'waste'],
      '410': ['assembly', 'buyer', 'waste'], '156': ['source', 'assembly', 'buyer', 'waste'],
      '704': ['assembly', 'waste'], '356': ['assembly', 'buyer', 'waste'], '360': ['source', 'assembly', 'buyer', 'waste'],
      '484': ['assembly', 'logistics', 'buyer', 'waste'], '792': ['assembly', 'logistics', 'buyer', 'waste'],
      '818': ['assembly'], '586': ['assembly', 'waste'], '050': ['assembly'],
      '784': ['logistics', 'buyer', 'waste'], '528': ['logistics', 'buyer'], '702': ['logistics'],
      '203': ['logistics'], '703': ['logistics'], '056': ['logistics'], '591': ['logistics'],
      '458': ['logistics'], '616': ['logistics', 'buyer', 'waste'], '682': ['logistics', 'buyer'],
      '276': ['logistics', 'buyer', 'waste'], '076': ['source', 'assembly', 'buyer', 'waste'],
      '826': ['buyer', 'waste'], '250': ['buyer', 'waste'], '380': ['buyer', 'waste'], '724': ['buyer', 'waste'],
      '764': ['buyer', 'waste'], '566': ['buyer', 'waste'], '288': ['waste'],
    },
    mapLabels: [
      ['DR Congo', 563, 258, 'source'], ['Australia', 872, 319, 'source'], ['Chile', 303, 342, 'source'], ['Peru', 292, 278, 'source'],
      ['Taiwan', 836, 185, 'component'], ['Japan', 883, 147, 'component'], ['China', 789, 153, 'assembly'],
      ['Vietnam', 800, 206, 'assembly'], ['India', 719, 189, 'assembly'], ['UAE', 650, 183, 'logistics'],
      ['Netherlands', 514, 106, 'logistics'], ['Singapore', 789, 247, 'logistics'], ['United States', 222, 144, 'buyer'], ['Brazil', 356, 278, 'buyer'],
    ],
  },
  {
    id: 'metal-knife',
    name: 'Metal knife',
    aliases: ['knife', 'metal knife', 'kitchen knife', 'kitchen blade', 'chef knife', 'chefs knife', "chef's knife", 'cook knife', 'cooks knife', 'table knife', 'dinner knife', 'cutlery knife', 'stainless knife', 'stainless steel knife', 'steel knife', 'paring knife', 'utility knife', 'slicing knife', 'carving knife', 'butter knife', 'metal blade'],
    category: 'Kitchen tool',
    descriptor: 'Kitchen and dining',
    portable: true,
    powered: false,
    setting: 'kitchen use',
    finishedPrice: {
      range: '$5–$300 per unit',
      basis: 'Typical new retail range from basic stamped utensils to premium forged kitchen knives.',
      tiers: [['Basic', '$5–$25'], ['Everyday', '$25–$80'], ['Premium', '$80–$180'], ['Specialty', '$180–$300']],
    },
    guessMaterials: ['Steel', 'Chromium', 'Nickel', 'Manganese', 'Molybdenum'],
    materials: [
      ['Iron / steel', 139, 0.15], ['Chromium', 23.4, 10], ['Nickel', 9, 16.05],
      ['Manganese', 3.6, 2], ['Molybdenum', 1.8, 50], ['Silicon', 1.8, 2.5], ['Carbon', 1.4, 0.20],
    ],
    stages: {
      sources: [['Australia', 24, null, ['Iron ore', 'manganese', 'nickel']], ['South Africa', 16, null, ['Chromium', 'manganese', 'iron ore']], ['Indonesia', 14, null, ['Nickel', 'iron ore']], ['Brazil', 10, null, ['Iron ore', 'manganese']], ['China', 9, null, ['Molybdenum', 'silicon', 'iron ore']], ['India', 8, null, ['Iron ore', 'manganese', 'chromium']], ['Philippines', 5, null, ['Nickel', 'chromium']], ['Kazakhstan', 4, null, ['Chromium', 'molybdenum']], ['Zimbabwe', 3, null, ['Chromium', 'nickel']], ['Canada', 2, null, ['Nickel', 'iron ore', 'molybdenum']], ['Finland', 1, null, ['Chromium', 'nickel']], ['Other', 4, null, ['Carbon', 'silicon', 'alloying metals']]],
      components: [
        ['China', 34, null, ['Stamped blades', 'molded handles', 'fasteners'], '156'],
        ['Germany', 13, null, ['Forged blades', 'steel blanks'], '276'],
        ['Japan', 12, null, ['Blade steel', 'forged blades', 'wood handles'], '392'],
        ['India', 9, null, ['Steel blanks', 'molded handles'], '356'],
        ['Italy', 6, null, ['Forged blades', 'handles'], '380'],
        ['Brazil', 5, null, ['Steel blanks', 'wood handles'], '076'],
        ['Vietnam', 4, null, ['Stamped blades', 'handles'], '704'],
        ['Switzerland', 3, null, ['Precision blades', 'handle parts'], '756'],
        ['United States', 3, null, ['Blade blanks', 'composite handles'], '840'],
        ['Taiwan', 3, null, ['Stamped blades', 'fasteners'], '158'],
        ['France', 2, null, ['Forged blades', 'handles'], '250'],
        ['Portugal', 2, null, ['Cork and wood handles', 'blade parts'], '620'],
        ['Other', 4, null, ['Pins', 'bolsters', 'minor handle parts'], null],
      ],
      assembly: [['China', 48], ['Germany', 9], ['Japan', 8], ['Brazil', 6], ['Vietnam', 5], ['India', 5], ['Switzerland', 4], ['Italy', 3], ['Portugal', 2], ['Spain', 2], ['France', 1.5], ['Taiwan', 1.5], ['Pakistan', 1], ['Other', 4]],
      logistics: [['Hong Kong', 22], ['Germany', 13], ['Netherlands', 12], ['United Arab Emirates', 9], ['Singapore', 8], ['Belgium', 7], ['United States', 6], ['Switzerland', 5], ['Italy', 4], ['Turkey', 3], ['Mexico', 3], ['Panama', 2], ['Poland', 2], ['Other', 4]],
      buyers: [['United States', 15], ['China', 10], ['Germany', 7], ['Japan', 6], ['United Kingdom', 5], ['France', 5], ['Brazil', 5], ['India', 5], ['Italy', 4], ['Canada', 4], ['Spain', 4], ['South Korea', 3], ['Mexico', 3], ['Australia', 3], ['Netherlands', 2.5], ['Russia', 2.5], ['Turkey', 2], ['Saudi Arabia', 2], ['South Africa', 1.5], ['Sweden', 1.5], ['Switzerland', 1.5], ['Poland', 1.5], ['Indonesia', 1], ['United Arab Emirates', 1], ['Other', 4]],
      waste: [['China', 17], ['United States', 10.5], ['India', 10], ['Germany', 7], ['Japan', 6], ['Turkey', 5], ['Italy', 4], ['United Kingdom', 4], ['France', 4], ['Brazil', 4], ['Mexico', 3], ['South Korea', 3], ['Spain', 3], ['Poland', 2.5], ['Russia', 2.5], ['Canada', 2], ['Australia', 2], ['Netherlands', 1.5], ['Belgium', 1.5], ['South Africa', 1.5], ['United Arab Emirates', 1], ['Indonesia', 1], ['Other', 4]],
    },
    feedback: [
      'It is a hand-held tool used at a table or on a work surface.',
      'Almost all of its mass is an iron alloy designed to resist corrosion.',
      'Chromium protects its surface, while carbon helps its edge stay hard.',
      'It has a fixed cutting edge and is commonly found in a kitchen.',
    ],
    mapRoles: {
      '036': ['source', 'buyer', 'waste'], '710': ['source', 'buyer', 'waste'], '360': ['source', 'buyer', 'waste'],
      '076': ['source', 'assembly', 'buyer', 'waste'], '156': ['source', 'assembly', 'buyer', 'waste'],
      '356': ['source', 'assembly', 'buyer', 'waste'], '608': ['source'], '398': ['source'],
      '716': ['source'], '124': ['source', 'buyer', 'waste'], '246': ['source'],
      '276': ['assembly', 'logistics', 'buyer', 'waste'], '392': ['assembly', 'buyer', 'waste'],
      '704': ['assembly'], '756': ['assembly', 'logistics', 'buyer'], '380': ['assembly', 'logistics', 'buyer', 'waste'],
      '620': ['assembly'], '724': ['assembly', 'buyer', 'waste'], '250': ['assembly', 'buyer', 'waste'],
      '158': ['assembly'], '586': ['assembly'], '344': ['logistics'], '528': ['logistics', 'buyer', 'waste'],
      '784': ['logistics', 'buyer', 'waste'], '702': ['logistics'], '056': ['logistics', 'waste'],
      '840': ['logistics', 'buyer', 'waste'], '792': ['logistics', 'buyer', 'waste'],
      '484': ['logistics', 'buyer', 'waste'], '591': ['logistics'], '616': ['logistics', 'buyer', 'waste'],
      '826': ['buyer', 'waste'], '410': ['buyer', 'waste'], '643': ['buyer', 'waste'],
      '682': ['buyer'], '752': ['buyer'],
    },
    mapLabels: [
      ['Australia', 872, 319, 'source'], ['South Africa', 548, 337, 'source'], ['Indonesia', 823, 278, 'source'],
      ['China', 789, 153, 'assembly'], ['Germany', 528, 107, 'assembly'], ['Japan', 883, 147, 'assembly'],
      ['Brazil', 356, 278, 'assembly'], ['Hong Kong', 807, 181, 'logistics'], ['Netherlands', 514, 106, 'logistics'],
      ['United States', 222, 144, 'buyer'], ['India', 719, 189, 'buyer'],
    ],
  },
  {
    id: 'office-chair',
    name: 'Office chair',
    aliases: ['chair', 'office seat', 'desk chair', 'desk seat', 'task chair', 'task seat', 'computer chair', 'computer desk chair', 'swivel chair', 'swivel office chair', 'rolling chair', 'rolling office chair', 'wheeled chair', 'wheeled office chair', 'ergonomic chair', 'ergonomic office chair', 'work chair', 'workplace chair', 'operator chair', 'secretarial chair', 'adjustable chair', 'adjustable office chair'],
    category: 'Furniture',
    descriptor: 'Workplace furnishing',
    portable: false,
    powered: false,
    setting: 'workplace use',
    finishedPrice: {
      range: '$60–$1,500 per unit',
      basis: 'Typical new retail range; refurbished premium chairs can cost substantially less.',
      tiers: [['Basic', '$60–$150'], ['Everyday', '$150–$350'], ['Ergonomic', '$350–$800'], ['Premium', '$800–$1,500']],
    },
    guessMaterials: ['Nylon', 'Steel', 'Polypropylene', 'Aluminum', 'Polyurethane'],
    materials: [
      ['Nylon', 5957, 2.20], ['Steel', 4171, 0.70], ['Polypropylene', 2216, 1.10],
      ['Aluminum', 625, 2.80], ['Polyurethane', 563, 2.50], ['Polyoxymethylene', 261, 2.70],
      ['Polyester textile', 90, 1.30], ['Glass fiber', 55, 1.00],
      ['Thermoplastic elastomer', 35, 2.20], ['Zinc alloy', 20, 3.00],
      ['Powder coatings', 12, 4.00], ['Adhesives', 7, 3.00],
    ],
    stages: {
      sources: [['China', 18, null, ['Steel', 'nylon feedstocks', 'polypropylene', 'aluminum']], ['Australia', 12, null, ['Iron ore', 'bauxite', 'nickel']], ['Brazil', 10, null, ['Iron ore', 'bauxite']], ['India', 9, null, ['Iron ore', 'steel', 'polypropylene feedstocks']], ['Guinea', 7, null, ['Bauxite']], ['Indonesia', 7, null, ['Nickel', 'petrochemical feedstocks']], ['South Africa', 6, null, ['Chromium', 'manganese', 'iron ore']], ['Russia', 5, null, ['Nickel', 'aluminum', 'petrochemical feedstocks']], ['Canada', 4, null, ['Aluminum', 'steel', 'petrochemical feedstocks']], ['United States', 4, null, ['Polyurethane feedstocks', 'steel', 'adhesives']], ['Saudi Arabia', 4, null, ['Polypropylene feedstocks', 'nylon feedstocks']], ['Vietnam', 3, null, ['Rubber', 'steel']], ['Chile', 3, null, ['Copper', 'molybdenum']], ['Sweden', 2, null, ['Iron ore', 'steel']], ['Finland', 2, null, ['Chromium', 'nickel']], ['Other', 4, null, ['Glass fiber', 'zinc', 'coating minerals']]],
      components: [
        ['China', 30, null, ['Bases', 'casters', 'gas lifts', 'molded shells'], '156'],
        ['United States', 12, null, ['Tilt mechanisms', 'foam', 'upholstery'], '840'],
        ['Germany', 9, null, ['Mechanisms', 'gas lifts', 'mesh'], '276'],
        ['Italy', 8, null, ['Molded shells', 'upholstery'], '380'],
        ['Poland', 7, null, ['Frames', 'foam', 'upholstery'], '616'],
        ['Taiwan', 6, null, ['Casters', 'seat mechanisms'], '158'],
        ['South Korea', 5, null, ['Mesh', 'molded parts'], '410'],
        ['Canada', 4, null, ['Wood shells', 'upholstery'], '124'],
        ['Mexico', 4, null, ['Metal frames', 'foam'], '484'],
        ['Vietnam', 4, null, ['Wood parts', 'upholstery'], '704'],
        ['Czechia', 3, null, ['Mechanisms', 'metal frames'], '203'],
        ['Turkey', 2, null, ['Textiles', 'foam'], '792'],
        ['Other', 6, null, ['Armrests', 'fasteners', 'minor fittings'], null],
      ],
      assembly: [['China', 34], ['United States', 12], ['Germany', 8], ['Poland', 7], ['Italy', 6], ['Canada', 5], ['Mexico', 5], ['Vietnam', 4], ['Turkey', 3], ['Czechia', 3], ['Romania', 2.5], ['Portugal', 2], ['Japan', 2], ['India', 2], ['Brazil', 1.5], ['Other', 3]],
      logistics: [['Germany', 14], ['Netherlands', 13], ['Belgium', 10], ['United States', 9], ['Singapore', 8], ['United Arab Emirates', 8], ['Poland', 6], ['Hong Kong', 6], ['Mexico', 5], ['Turkey', 4], ['Panama', 3], ['Czechia', 3], ['Malaysia', 3], ['Canada', 2], ['Other', 6]],
      buyers: [['United States', 19], ['Germany', 8], ['United Kingdom', 6], ['France', 5.5], ['China', 6], ['Japan', 4.5], ['Canada', 4.5], ['Italy', 4], ['Netherlands', 3.5], ['Spain', 3.5], ['Australia', 3], ['Poland', 3], ['Sweden', 2.5], ['South Korea', 2.5], ['Belgium', 2.5], ['Switzerland', 2], ['Austria', 2], ['Brazil', 2], ['Mexico', 2], ['India', 3], ['Norway', 1.5], ['Denmark', 1.5], ['United Arab Emirates', 1.5], ['Saudi Arabia', 1.5], ['South Africa', 1], ['Other', 4]],
      waste: [['United States', 14], ['China', 9], ['Germany', 8], ['United Kingdom', 6], ['France', 5], ['Japan', 5], ['Canada', 4.5], ['Italy', 4], ['India', 4], ['Brazil', 4], ['Poland', 3.5], ['Spain', 3.5], ['Netherlands', 3], ['Mexico', 3], ['Australia', 3], ['Russia', 2.5], ['Turkey', 2.5], ['South Korea', 2.5], ['Belgium', 2], ['Indonesia', 2], ['South Africa', 1.5], ['Vietnam', 1.5], ['United Arab Emirates', 1], ['Ghana', 1], ['Other', 4]],
    },
    feedback: [
      'It is built to stay in one room and support one person for long periods.',
      'Its largest material share is engineered nylon, followed by steel.',
      'Adjustment mechanisms and rolling movement matter more than portability.',
      'It usually has a backrest, a height-adjustable seat and a five-point base.',
    ],
    mapRoles: {
      '156': ['source', 'assembly', 'buyer', 'waste'], '036': ['source', 'buyer', 'waste'],
      '076': ['source', 'assembly', 'buyer', 'waste'], '356': ['source', 'assembly', 'buyer', 'waste'],
      '324': ['source'], '360': ['source', 'waste'], '710': ['source', 'buyer', 'waste'],
      '643': ['source', 'waste'], '124': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '682': ['source', 'buyer'],
      '704': ['source', 'assembly', 'waste'], '152': ['source'], '752': ['source', 'buyer'],
      '246': ['source'], '276': ['assembly', 'logistics', 'buyer', 'waste'],
      '616': ['assembly', 'logistics', 'buyer', 'waste'], '380': ['assembly', 'buyer', 'waste'],
      '484': ['assembly', 'logistics', 'buyer', 'waste'], '792': ['assembly', 'logistics', 'waste'],
      '203': ['assembly', 'logistics'], '642': ['assembly'], '620': ['assembly'],
      '392': ['assembly', 'buyer', 'waste'], '528': ['logistics', 'buyer', 'waste'],
      '056': ['logistics', 'buyer', 'waste'], '702': ['logistics'], '784': ['logistics', 'buyer', 'waste'],
      '344': ['logistics'], '591': ['logistics'], '458': ['logistics'],
      '826': ['buyer', 'waste'], '250': ['buyer', 'waste'], '724': ['buyer', 'waste'],
      '410': ['buyer', 'waste'], '756': ['buyer'], '040': ['buyer'], '578': ['buyer'],
      '208': ['buyer'], '288': ['waste'],
    },
    mapLabels: [
      ['Australia', 872, 319, 'source'], ['Brazil', 356, 278, 'source'], ['Guinea', 487, 226, 'source'],
      ['China', 789, 153, 'assembly'], ['United States', 222, 144, 'assembly'], ['Germany', 528, 107, 'assembly'],
      ['Poland', 553, 101, 'assembly'], ['Netherlands', 514, 106, 'logistics'],
      ['Singapore', 789, 247, 'logistics'], ['United Kingdom', 493, 96, 'buyer'],
      ['Japan', 883, 147, 'buyer'], ['Ghana', 506, 238, 'waste'],
    ],
  },
  {
    id: 'glass-bottle',
    name: 'Glass bottle',
    aliases: ['bottle', 'glass bottle', 'glass container', 'glass drinks bottle', 'glass drink bottle', 'glass beverage bottle', 'beverage bottle', 'drink bottle', 'water bottle', 'glass water bottle', 'wine bottle', 'beer bottle', 'soda bottle', 'soft drink bottle', 'juice bottle', 'milk bottle', 'spirits bottle', 'liquor bottle', 'champagne bottle', 'reusable glass bottle', 'refillable glass bottle', 'returnable bottle'],
    category: 'Packaging',
    descriptor: 'Food and drink packaging',
    portable: true,
    powered: false,
    setting: 'food and drink use',
    finishedPrice: {
      range: '$0.25–$8 per unit',
      basis: 'Indicative empty-container price: high-volume wholesale at the low end, small retail packs and reusable designs at the high end.',
      tiers: [['Bulk standard', '$0.25–$0.75'], ['Small wholesale', '$0.75–$1.50'], ['Retail empty', '$1.50–$4'], ['Reusable / design', '$4–$8']],
    },
    guessMaterials: ['Recycled glass', 'Silica sand', 'Soda ash', 'Limestone', 'Steel'],
    materials: [
      ['Recycled glass cullet', 102, 0.06], ['Silica sand', 56, 0.05], ['Soda ash', 18, 0.30],
      ['Limestone', 10, 0.12], ['Dolomite', 5, 0.15], ['Steel', 3, 0.70],
      ['Paper', 2, 0.90], ['Plastic liner', 1.5, 1.50], ['Protective coatings', 1, 4.00],
      ['Adhesive', 0.5, 3.00], ['Printing inks', 0.5, 8.00], ['Mineral colorants', 0.5, 2.00],
    ],
    stages: {
      sources: [['China', 17, null, ['Silica sand', 'soda ash', 'limestone', 'colorants']], ['United States', 12, null, ['Soda ash', 'silica sand', 'recycled cullet']], ['Turkey', 9, null, ['Soda ash', 'limestone', 'dolomite']], ['India', 8, null, ['Silica sand', 'limestone', 'dolomite']], ['Germany', 7, null, ['Recycled cullet', 'silica sand', 'paper']], ['France', 6, null, ['Recycled cullet', 'limestone', 'paper']], ['Italy', 6, null, ['Recycled cullet', 'silica sand', 'coatings']], ['Spain', 5, null, ['Recycled cullet', 'silica sand', 'limestone']], ['Brazil', 5, null, ['Silica sand', 'limestone', 'paper']], ['Mexico', 4, null, ['Silica sand', 'soda ash', 'recycled cullet']], ['Australia', 4, null, ['Silica sand', 'limestone', 'recycled cullet']], ['South Africa', 4, null, ['Silica sand', 'limestone', 'colorants']], ['Egypt', 3, null, ['Silica sand', 'limestone']], ['Chile', 3, null, ['Silica sand', 'limestone']], ['Poland', 3, null, ['Recycled cullet', 'silica sand', 'paper']], ['Other', 4, null, ['Steel', 'plastic liner resin', 'inks', 'adhesives']]],
      components: [
        ['China', 22, null, ['Closures', 'labels', 'molded containers'], '156'],
        ['United States', 13, null, ['Closures', 'labels', 'glass containers'], '840'],
        ['Italy', 11, null, ['Glass containers', 'closures'], '380'],
        ['Germany', 9, null, ['Closures', 'labels', 'glass containers'], '276'],
        ['France', 8, null, ['Glass containers', 'labels'], '250'],
        ['Spain', 7, null, ['Glass containers', 'closures'], '724'],
        ['Mexico', 6, null, ['Glass containers', 'metal closures'], '484'],
        ['Turkey', 5, null, ['Glass containers', 'closures'], '792'],
        ['India', 5, null, ['Glass containers', 'closures'], '356'],
        ['Brazil', 4, null, ['Glass containers', 'labels'], '076'],
        ['Poland', 3, null, ['Glass containers', 'metal closures'], '616'],
        ['Portugal', 2, null, ['Glass containers', 'cork closures'], '620'],
        ['Other', 5, null, ['Liners', 'adhesives', 'minor label stock'], null],
      ],
      assembly: [['China', 20], ['United States', 12], ['Italy', 9], ['France', 8], ['Germany', 7], ['Spain', 6], ['Mexico', 6], ['Brazil', 5], ['India', 5], ['Russia', 4], ['Turkey', 4], ['Poland', 3], ['United Kingdom', 3], ['Japan', 2], ['South Africa', 2], ['Other', 4]],
      logistics: [['Netherlands', 14], ['Germany', 12], ['Belgium', 10], ['United States', 9], ['United Arab Emirates', 8], ['Singapore', 7], ['Mexico', 6], ['Spain', 5], ['France', 5], ['Panama', 4], ['United Kingdom', 4], ['Poland', 3], ['Turkey', 3], ['South Africa', 3], ['Other', 7]],
      buyers: [['United States', 14], ['China', 10], ['Germany', 7], ['France', 6], ['United Kingdom', 5], ['Italy', 5], ['Brazil', 4.5], ['Mexico', 4.5], ['Spain', 4], ['India', 4], ['Japan', 3.5], ['Russia', 3.5], ['Canada', 3], ['Turkey', 3], ['Poland', 2.5], ['South Africa', 2.5], ['Australia', 2], ['Netherlands', 2], ['Belgium', 2], ['Argentina', 2], ['Nigeria', 1.5], ['Indonesia', 1.5], ['Saudi Arabia', 1.5], ['United Arab Emirates', 1.5], ['Other', 4]],
      waste: [['China', 10], ['United States', 9], ['India', 7], ['Germany', 6], ['Brazil', 5], ['Mexico', 4], ['France', 5], ['United Kingdom', 5], ['Italy', 5], ['Russia', 4], ['Turkey', 4], ['Spain', 4], ['Japan', 3.5], ['Indonesia', 3.5], ['South Africa', 3], ['Nigeria', 3], ['Poland', 2.5], ['Canada', 2.5], ['Australia', 2], ['Netherlands', 2], ['Belgium', 2], ['Argentina', 2], ['Ghana', 1.5], ['United Arab Emirates', 1.5], ['Other', 3]],
    },
    feedback: [
      'It is portable packaging rather than a durable tool or device.',
      'More than half of its modeled mass can come from previously used material of the same kind.',
      'Silica sand, soda ash and limestone are melted together at high temperature.',
      'It is rigid, transparent or colored, and commonly sealed with a small closure.',
    ],
    mapRoles: {
      '156': ['source', 'assembly', 'buyer', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '792': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '356': ['source', 'assembly', 'buyer', 'waste'],
      '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '250': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '380': ['source', 'assembly', 'buyer', 'waste'], '724': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '076': ['source', 'assembly', 'buyer', 'waste'], '484': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '036': ['source', 'buyer', 'waste'], '710': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '818': ['source'], '152': ['source'], '616': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '643': ['assembly', 'buyer', 'waste'], '826': ['assembly', 'logistics', 'buyer', 'waste'],
      '392': ['assembly', 'buyer', 'waste'], '528': ['logistics', 'buyer', 'waste'],
      '056': ['logistics', 'buyer', 'waste'], '784': ['logistics', 'buyer', 'waste'],
      '702': ['logistics'], '591': ['logistics'], '124': ['buyer', 'waste'],
      '032': ['buyer', 'waste'], '566': ['buyer', 'waste'], '360': ['buyer', 'waste'],
      '682': ['buyer'], '288': ['waste'],
    },
    mapLabels: [
      ['China', 789, 153, 'source'], ['United States', 222, 144, 'source'], ['Turkey', 591, 142, 'source'],
      ['Italy', 535, 130, 'assembly'], ['France', 509, 123, 'assembly'], ['Mexico', 191, 197, 'assembly'],
      ['Netherlands', 514, 106, 'logistics'], ['Belgium', 510, 111, 'logistics'],
      ['Brazil', 356, 278, 'buyer'], ['India', 719, 189, 'buyer'], ['Ghana', 506, 238, 'waste'],
    ],
  },
  {
    id: 'paper',
    name: 'Paper',
    aliases: ['paper', 'sheet of paper', 'paper sheet', 'piece of paper', 'writing paper', 'printing paper', 'printer paper', 'printer sheet', 'copy paper', 'copier paper', 'office paper', 'office copy paper', 'white paper', 'blank paper', 'plain paper', 'a4 paper', 'a4 sheet', 'a4 printer paper', 'a4 copy paper', 'letter paper', 'letter-size paper', 'notebook paper', 'writing sheet', 'printout paper', 'ream paper'],
    category: 'Stationery',
    descriptor: 'Writing and printing material',
    portable: true,
    powered: false,
    setting: 'office, school and home use',
    finishedPrice: {
      range: '$0.01–$0.15 per unit',
      basis: 'Typical range for one blank A4 sheet: bulk office reams at the low end and premium, recycled or specialty sheets at the high end.',
      tiers: [['Bulk office', '$0.01–$0.03'], ['Everyday retail', '$0.03–$0.06'], ['Premium / recycled', '$0.06–$0.10'], ['Specialty sheet', '$0.10–$0.15']],
    },
    guessMaterials: ['Cellulose fiber', 'Calcium carbonate', 'Kaolin clay', 'Starch', 'Sizing agents'],
    materials: [
      ['Cellulose fiber', 3.82, 1.20], ['Calcium carbonate', 0.70, 0.15],
      ['Kaolin clay', 0.18, 0.18], ['Starch', 0.10, 0.55],
      ['Retained moisture', 0.10, 0.001], ['Sizing agents', 0.04, 2.50],
      ['Optical brightener', 0.02, 6.00], ['Retention aids', 0.02, 3.00],
      ['Dyes and pigments', 0.02, 4.00],
    ],
    stages: {
      sources: [['Brazil', 16, null, ['Eucalyptus pulp', 'starch']], ['United States', 14, null, ['Softwood pulp', 'recovered fiber']], ['Canada', 11, null, ['Softwood pulp', 'calcium carbonate']], ['Sweden', 9, null, ['Softwood pulp', 'recovered fiber']], ['Finland', 9, null, ['Softwood pulp', 'calcium carbonate']], ['Indonesia', 8, null, ['Acacia pulp', 'starch']], ['Chile', 7, null, ['Eucalyptus pulp', 'softwood pulp']], ['Uruguay', 5, null, ['Eucalyptus pulp']], ['Russia', 5, null, ['Softwood pulp', 'birch pulp']], ['Germany', 4, null, ['Recovered fiber', 'kaolin clay']], ['China', 4, null, ['Recovered fiber', 'calcium carbonate']], ['Australia', 2, null, ['Eucalyptus pulp', 'kaolin clay']], ['Portugal', 2, null, ['Eucalyptus pulp']], ['New Zealand', 1, null, ['Softwood pulp']], ['Other', 3, null, ['Starch', 'sizing agents', 'brighteners', 'pigments']]],
      components: [
        ['Brazil', 17, null, ['Bleached eucalyptus pulp', 'market pulp'], '076'],
        ['Canada', 13, null, ['Softwood kraft pulp', 'recycled fibre'], '124'],
        ['United States', 13, null, ['Pulp', 'recycled fibre', 'mineral fillers'], '840'],
        ['Finland', 10, null, ['Market pulp', 'coating materials'], '246'],
        ['Sweden', 9, null, ['Softwood pulp', 'mineral fillers'], '752'],
        ['Indonesia', 8, null, ['Hardwood pulp', 'starch'], '360'],
        ['Chile', 7, null, ['Softwood and hardwood pulp'], '152'],
        ['Uruguay', 5, null, ['Eucalyptus pulp'], '858'],
        ['Germany', 4, null, ['Pigments', 'sizing agents'], '276'],
        ['China', 4, null, ['Calcium carbonate', 'optical brighteners'], '156'],
        ['Austria', 3, null, ['Market pulp'], '040'],
        ['Portugal', 3, null, ['Eucalyptus pulp'], '620'],
        ['Other', 4, null, ['Starch', 'retention aids', 'minor additives'], null],
      ],
      assembly: [['China', 33], ['United States', 15], ['India', 5], ['Japan', 5], ['Germany', 5], ['Indonesia', 3], ['Brazil', 3], ['South Korea', 3], ['Russia', 3], ['Finland', 3], ['Sweden', 3], ['Canada', 2.5], ['Italy', 2], ['France', 2], ['Poland', 1.5], ['Austria', 1.5], ['Portugal', 1.5], ['Other', 8]],
      logistics: [['Germany', 11], ['United States', 9], ['China', 9], ['Sweden', 7], ['Finland', 6], ['Canada', 5], ['Indonesia', 5], ['Netherlands', 6], ['Belgium', 4], ['Singapore', 4], ['Austria', 3], ['France', 3], ['Russia', 3], ['Italy', 3], ['Malaysia', 3], ['United Arab Emirates', 3], ['Poland', 2], ['Turkey', 2], ['Mexico', 2], ['United Kingdom', 2], ['Brazil', 2], ['Portugal', 2], ['Panama', 1], ['South Africa', 1], ['Other', 2]],
      buyers: [['China', 12.5], ['United States', 11], ['Germany', 8], ['United Kingdom', 5], ['France', 4], ['India', 4], ['Japan', 4], ['Italy', 4], ['Poland', 4], ['Mexico', 3], ['Canada', 3], ['Spain', 3], ['Nigeria', 3], ['South Korea', 3], ['Brazil', 3], ['Netherlands', 3], ['Turkey', 2.5], ['Indonesia', 2.5], ['Australia', 2.5], ['Russia', 2], ['Belgium', 2], ['Austria', 2], ['South Africa', 2], ['Sweden', 1.5], ['United Arab Emirates', 1.5], ['Other', 4]],
      waste: [['China', 17], ['United States', 13], ['India', 7], ['Japan', 5], ['Germany', 5], ['United Kingdom', 4], ['France', 4], ['Brazil', 4], ['Indonesia', 3.5], ['Russia', 3.5], ['Italy', 3], ['Mexico', 3], ['South Korea', 3], ['Spain', 2.5], ['Poland', 2.5], ['Canada', 2], ['Turkey', 2], ['Nigeria', 2], ['Australia', 2], ['Netherlands', 1.5], ['Belgium', 1.5], ['South Africa', 1.5], ['Sweden', 1.5], ['Malaysia', 1], ['United Arab Emirates', 1], ['Other', 4]],
    },
    feedback: [
      'It is a very light, flat everyday medium found in offices, schools and homes.',
      'Most of its mass is cellulose fiber pressed into a thin, flexible layer.',
      'Mineral fillers improve brightness and opacity, while starch helps its surface behave consistently.',
      'A common version measures 210 × 297 mm and is made for writing, drawing or printing.',
    ],
    mapRoles: {
      '076': ['source', 'assembly', 'buyer', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '124': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '752': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '246': ['source', 'assembly', 'logistics'], '360': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '152': ['source'], '858': ['source'], '643': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '156': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '036': ['source', 'buyer', 'waste'], '620': ['source', 'assembly', 'logistics'], '554': ['source'],
      '356': ['assembly', 'buyer', 'waste'], '392': ['assembly', 'buyer', 'waste'], '410': ['assembly', 'buyer', 'waste'],
      '380': ['assembly', 'logistics', 'buyer', 'waste'], '250': ['assembly', 'logistics', 'buyer', 'waste'],
      '616': ['assembly', 'logistics', 'buyer', 'waste'], '040': ['assembly', 'logistics', 'buyer'],
      '528': ['logistics', 'buyer', 'waste'], '056': ['logistics', 'buyer', 'waste'], '702': ['logistics'],
      '458': ['logistics', 'waste'], '784': ['logistics', 'buyer', 'waste'], '792': ['logistics', 'buyer', 'waste'],
      '484': ['logistics', 'buyer', 'waste'], '826': ['logistics', 'buyer', 'waste'], '710': ['logistics', 'buyer', 'waste'],
      '724': ['buyer', 'waste'], '566': ['buyer', 'waste'],
    },
    mapLabels: [
      ['Brazil', 356, 278, 'source'], ['Canada', 214, 97, 'source'], ['Sweden', 544, 75, 'source'],
      ['Finland', 570, 73, 'component'], ['China', 789, 153, 'assembly'], ['United States', 222, 144, 'assembly'],
      ['India', 719, 189, 'assembly'], ['Germany', 528, 107, 'logistics'], ['Netherlands', 514, 106, 'logistics'],
      ['United Kingdom', 493, 96, 'buyer'], ['Nigeria', 500, 241, 'buyer'], ['Indonesia', 823, 278, 'waste'],
    ],
  },
  {
    id: 'ballpoint-pen',
    name: 'Ballpoint pen',
    aliases: ['pen', 'ballpoint pen', 'ball point pen', 'ball pen', 'biro', 'biro pen', 'writing pen', 'ink pen', 'plastic pen', 'disposable pen', 'stick pen', 'capped pen', 'click pen', 'retractable pen', 'office pen', 'school pen', 'blue pen', 'black pen', 'red pen', 'bic', 'bic pen', 'bic biro', 'bic cristal', 'cristal pen', 'roller pen', 'writing instrument'],
    category: 'Stationery',
    descriptor: 'Hand-held writing instrument',
    portable: true,
    powered: false,
    setting: 'office, school and home use',
    finishedPrice: {
      range: '$0.10–$5 per unit',
      basis: 'Typical new retail range for one mass-market ballpoint: bulk stick pens at the low end and branded refillable or multi-function models at the high end.',
      tiers: [['Bulk stick', '$0.10–$0.30'], ['Everyday branded', '$0.30–$1'], ['Refillable', '$1–$3'], ['Multi-function', '$3–$5']],
    },
    guessMaterials: ['Polystyrene', 'Polypropylene', 'Ink', 'Brass', 'Tungsten carbide'],
    materials: [
      ['Polystyrene', 3.45, 1.35], ['Polypropylene', 1.35, 1.15],
      ['Oil-based ink', 0.35, 8.00], ['Brass', 0.20, 6.00],
      ['Steel', 0.08, 0.70], ['Tungsten carbide', 0.05, 45.00],
      ['Pigments and dyes', 0.02, 12.00],
    ],
    stages: {
      sources: [['China', 19, null, ['Tungsten', 'plastics', 'pigments']], ['United States', 14, null, ['Styrene feedstocks', 'polypropylene']], ['Saudi Arabia', 12, null, ['Petrochemical feedstocks']], ['Chile', 10, null, ['Copper for brass']], ['Australia', 8, null, ['Zinc', 'iron ore']], ['Indonesia', 7, null, ['Petrochemical feedstocks', 'tin']], ['Peru', 6, null, ['Copper', 'zinc']], ['India', 5, null, ['Pigments', 'dyes', 'plastics']], ['Vietnam', 4, null, ['Tungsten']], ['Brazil', 3, null, ['Iron ore', 'petrochemical feedstocks']], ['South Africa', 3, null, ['Iron ore', 'manganese']], ['Rwanda', 2, null, ['Tungsten']], ['Bolivia', 2, null, ['Tungsten', 'zinc']], ['Germany', 1, null, ['Specialty dyes', 'ink additives']], ['Other', 4, null, ['Solvents', 'resins', 'lubricants']]],
      components: [
        ['China', 35, null, ['Barrels', 'ink reservoirs', 'tip assemblies'], '156'],
        ['Japan', 15, null, ['Ink', 'ball-tip assemblies'], '392'],
        ['Germany', 9, null, ['Ink', 'precision tips', 'polymers'], '276'],
        ['France', 7, null, ['Ink systems', 'molded parts'], '250'],
        ['United States', 6, null, ['Inks', 'engineering polymers'], '840'],
        ['India', 6, null, ['Barrels', 'ink', 'tips'], '356'],
        ['Switzerland', 4, null, ['Precision tips', 'specialty ink'], '756'],
        ['Italy', 4, null, ['Molded parts', 'metal clips'], '380'],
        ['Mexico', 3, null, ['Barrels', 'packaging parts'], '484'],
        ['South Korea', 3, null, ['Inks', 'polymers'], '410'],
        ['Taiwan', 3, null, ['Tips', 'molded parts'], '158'],
        ['Other', 5, null, ['Springs', 'plugs', 'minor fittings'], null],
      ],
      assembly: [['China', 34], ['Japan', 12], ['France', 8], ['Germany', 7], ['Mexico', 6], ['India', 5], ['United States', 5], ['Italy', 3], ['Switzerland', 3], ['Slovakia', 2.5], ['Poland', 2], ['Czechia', 2], ['Spain', 1.5], ['Netherlands', 1.5], ['Tunisia', 1], ['South Korea', 1], ['Kenya', 0.5], ['Turkey', 0.5], ['Other', 4.5]],
      logistics: [['Hong Kong', 16], ['Netherlands', 12], ['Germany', 10], ['Singapore', 8], ['United States', 7], ['Belgium', 6], ['United Arab Emirates', 5], ['Mexico', 5], ['France', 4], ['China', 4], ['Poland', 3], ['Spain', 3], ['United Kingdom', 3], ['Japan', 3], ['Panama', 2], ['Turkey', 2], ['Malaysia', 2], ['Canada', 2], ['South Africa', 1], ['Chile', 1], ['Other', 1]],
      buyers: [['United States', 20], ['France', 8], ['Germany', 6], ['Mexico', 5], ['United Kingdom', 4], ['Italy', 4], ['China', 4], ['Spain', 4], ['Netherlands', 3.5], ['Poland', 3.5], ['Canada', 3], ['South Korea', 3], ['Czechia', 3], ['Japan', 3], ['Saudi Arabia', 2.5], ['Switzerland', 2.5], ['Australia', 2.5], ['Indonesia', 2], ['Brazil', 2], ['Thailand', 2], ['Belgium', 2], ['India', 2], ['Romania', 1.5], ['Singapore', 1.5], ['South Africa', 1.5], ['Other', 4]],
      waste: [['China', 15], ['United States', 11], ['India', 7], ['France', 5], ['Germany', 5], ['Mexico', 4], ['United Kingdom', 4], ['Italy', 4], ['Indonesia', 3.5], ['Brazil', 3.5], ['Japan', 3], ['Spain', 3], ['Poland', 3], ['South Korea', 3], ['Canada', 2.5], ['Turkey', 2.5], ['Thailand', 2.5], ['Australia', 2], ['Russia', 2], ['South Africa', 2], ['Malaysia', 2], ['Nigeria', 2], ['Netherlands', 1.5], ['Belgium', 1.5], ['Philippines', 1.5], ['Other', 4]],
    },
    feedback: [
      'It is a small hand-held object used repeatedly at desks, schools and counters.',
      'Most of its mass is molded plastic, with tiny metal parts concentrated at one end.',
      'A viscous colored liquid moves through a narrow internal tube during use.',
      'A rolling carbide sphere transfers the liquid onto a surface to form lines and words.',
    ],
    mapRoles: {
      '156': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '682': ['source', 'buyer'], '152': ['source', 'logistics'], '036': ['source', 'buyer', 'waste'],
      '360': ['source', 'buyer', 'waste'], '604': ['source'], '356': ['source', 'assembly', 'buyer', 'waste'],
      '704': ['source'], '076': ['source', 'buyer', 'waste'], '710': ['source', 'logistics', 'buyer', 'waste'],
      '646': ['source'], '068': ['source'], '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '392': ['assembly', 'logistics', 'buyer', 'waste'], '250': ['assembly', 'logistics', 'buyer', 'waste'],
      '484': ['assembly', 'logistics', 'buyer', 'waste'], '380': ['assembly', 'buyer', 'waste'],
      '756': ['assembly', 'buyer'], '703': ['assembly'], '616': ['assembly', 'logistics', 'buyer', 'waste'],
      '203': ['assembly', 'buyer'], '724': ['assembly', 'logistics', 'buyer', 'waste'], '528': ['assembly', 'logistics', 'buyer', 'waste'],
      '788': ['assembly'], '410': ['assembly', 'buyer', 'waste'], '404': ['assembly'], '792': ['assembly', 'logistics', 'waste'],
      '344': ['logistics'], '702': ['logistics', 'buyer'], '056': ['logistics', 'buyer', 'waste'],
      '784': ['logistics'], '591': ['logistics'], '826': ['logistics', 'buyer', 'waste'], '458': ['logistics', 'waste'],
      '124': ['logistics', 'buyer', 'waste'], '764': ['buyer', 'waste'], '642': ['buyer'],
      '643': ['waste'], '566': ['waste'], '608': ['waste'],
    },
    mapLabels: [
      ['China', 789, 153, 'source'], ['Saudi Arabia', 627, 187, 'source'], ['Chile', 328, 308, 'source'],
      ['Japan', 883, 147, 'assembly'], ['France', 509, 123, 'assembly'], ['Mexico', 191, 197, 'assembly'],
      ['Hong Kong', 807, 181, 'logistics'], ['Netherlands', 514, 106, 'logistics'], ['Singapore', 789, 247, 'logistics'],
      ['United States', 222, 144, 'buyer'], ['Brazil', 356, 278, 'waste'], ['India', 719, 189, 'waste'],
    ],
  },
  {
    id: 'beef',
    name: 'Beef',
    aliases: ['beef', 'beef meat', 'cow meat', 'cattle meat', 'red meat', 'steak', 'beef steak', 'raw beef', 'fresh beef', 'piece of beef', 'cut of beef', 'beef cut', 'sirloin', 'sirloin steak', 'rump steak', 'ribeye', 'rib eye', 'ribeye steak', 'fillet steak', 'tenderloin steak', 'minute steak', 'grilling steak', 'roast beef', 'beef portion', 'beef serving'],
    category: 'Food',
    descriptor: 'Fresh animal-protein food',
    portable: true,
    powered: false,
    setting: 'meal preparation and eating',
    finishedPrice: {
      range: '$2–$15 per unit',
      basis: 'Typical retail range for a 250 g raw serving: value cuts at the low end and premium steak cuts at the high end, excluding restaurant preparation.',
      tiers: [['Value cut', '$2–$4'], ['Everyday steak', '$4–$7'], ['Premium cut', '$7–$11'], ['Specialty / aged', '$11–$15']],
    },
    guessMaterials: ['Water', 'Muscle protein', 'Fat', 'Collagen', 'Minerals'],
    materials: [
      ['Water', 164, 0.001], ['Muscle protein', 50, 30.00],
      ['Fat', 27, 8.00], ['Collagen and connective protein', 5, 10.00],
      ['Minerals', 2.5, 1.00], ['Glycogen and sugars', 1, 2.00],
      ['Pigments and vitamins', 0.5, 20.00],
    ],
    stages: {
      sources: [['Brazil', 18, null, ['Pasture', 'soy feed', 'cattle']], ['United States', 15, null, ['Cattle', 'maize feed', 'pasture']], ['China', 10, null, ['Cattle', 'maize feed']], ['Argentina', 8, null, ['Pasture', 'cattle']], ['Australia', 8, null, ['Pasture', 'cattle']], ['India', 6, null, ['Bovines', 'crop residues']], ['Mexico', 5, null, ['Cattle', 'maize feed']], ['France', 4, null, ['Cattle', 'grass', 'grain']], ['Germany', 4, null, ['Cattle', 'grass', 'grain']], ['Ireland', 3, null, ['Grass', 'cattle']], ['Paraguay', 3, null, ['Pasture', 'cattle']], ['Canada', 4, null, ['Cattle', 'barley feed']], ['New Zealand', 4, null, ['Pasture', 'cattle']], ['Uruguay', 3, null, ['Pasture', 'cattle']], ['South Africa', 2, null, ['Cattle', 'maize feed']], ['Pakistan', 2, null, ['Cattle', 'fodder']], ['Other', 1, null, ['Feed grains', 'forage', 'water']]],
      assembly: [['Brazil', 20], ['United States', 19], ['China', 13], ['India', 7.5], ['Argentina', 5], ['Australia', 4.5], ['Mexico', 3.5], ['Russia', 2.5], ['Canada', 2], ['France', 2], ['Germany', 2], ['Italy', 1.5], ['Ireland', 1.5], ['United Kingdom', 1.5], ['New Zealand', 1.5], ['South Africa', 1], ['Japan', 1], ['Pakistan', 1], ['Paraguay', 1], ['Uruguay', 1], ['Colombia', 1], ['Turkey', 1], ['Egypt', 1], ['Indonesia', 1], ['Chile', 1], ['Other', 3]],
      logistics: [['Brazil', 18], ['Australia', 13], ['India', 7], ['United States', 7], ['Argentina', 7], ['New Zealand', 6], ['Canada', 5], ['Uruguay', 4], ['Paraguay', 4], ['Mexico', 3], ['Netherlands', 3], ['Germany', 3], ['Belgium', 2], ['United Arab Emirates', 2], ['Singapore', 2], ['Hong Kong', 2], ['Ireland', 1], ['Poland', 1], ['Spain', 1], ['France', 1], ['Chile', 1], ['South Africa', 1], ['Turkey', 1], ['Panama', 1], ['Other', 4]],
      buyers: [['China', 23], ['United States', 9], ['Japan', 7], ['South Korea', 6], ['Germany', 5], ['France', 5], ['Mexico', 4], ['United Kingdom', 4], ['Italy', 3], ['Netherlands', 3], ['Canada', 3], ['Chile', 3], ['Egypt', 2.5], ['Indonesia', 2.5], ['Spain', 2], ['Russia', 2], ['Saudi Arabia', 2], ['United Arab Emirates', 2], ['Brazil', 1.5], ['Australia', 1.5], ['Malaysia', 1.5], ['Philippines', 1.5], ['Turkey', 1], ['South Africa', 1], ['Other', 4]],
      waste: [['China', 19], ['United States', 10], ['Brazil', 8], ['India', 6], ['Germany', 5], ['France', 5], ['Japan', 4], ['Mexico', 4], ['United Kingdom', 3.5], ['Italy', 3.5], ['Argentina', 3], ['Russia', 3], ['Australia', 3], ['South Korea', 2.5], ['Canada', 2.5], ['Spain', 2], ['Indonesia', 2], ['Turkey', 2], ['South Africa', 1.5], ['Saudi Arabia', 1.5], ['Netherlands', 1.5], ['Egypt', 1.5], ['Malaysia', 1], ['United Arab Emirates', 1], ['Other', 4]],
    },
    feedback: [
      'It is a perishable everyday food rather than a durable manufactured object.',
      'Roughly two thirds of its mass is water, followed by protein and fat.',
      'Its upstream journey depends on pasture, feed crops, livestock and temperature-controlled transport.',
      'It is a red animal-derived food commonly sold as steaks, roasts or other cuts.',
    ],
    mapRoles: {
      '076': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '156': ['source', 'assembly', 'buyer', 'waste'], '032': ['source', 'assembly', 'logistics', 'waste'],
      '036': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '356': ['source', 'assembly', 'logistics', 'waste'],
      '484': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '250': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '372': ['source', 'assembly', 'logistics'],
      '600': ['source', 'assembly', 'logistics'], '124': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '554': ['source', 'assembly', 'logistics'], '858': ['source', 'assembly', 'logistics'], '710': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '586': ['source', 'assembly'], '643': ['assembly', 'buyer', 'waste'], '380': ['assembly', 'buyer', 'waste'],
      '826': ['assembly', 'buyer', 'waste'], '392': ['assembly', 'buyer', 'waste'], '170': ['assembly'],
      '792': ['assembly', 'logistics', 'buyer', 'waste'], '818': ['assembly', 'buyer', 'waste'],
      '360': ['assembly', 'buyer', 'waste'], '152': ['assembly', 'logistics', 'buyer'],
      '528': ['logistics', 'buyer', 'waste'], '056': ['logistics'], '784': ['logistics', 'buyer', 'waste'],
      '702': ['logistics'], '344': ['logistics'], '616': ['logistics'], '724': ['logistics', 'buyer', 'waste'],
      '591': ['logistics'], '410': ['buyer', 'waste'], '682': ['buyer', 'waste'], '458': ['buyer', 'waste'],
      '608': ['buyer'],
    },
    mapLabels: [
      ['Brazil', 356, 278, 'source'], ['United States', 222, 144, 'source'], ['Argentina', 332, 343, 'source'],
      ['China', 789, 153, 'assembly'], ['India', 719, 189, 'assembly'], ['Australia', 872, 319, 'logistics'],
      ['New Zealand', 934, 371, 'logistics'], ['Netherlands', 514, 106, 'logistics'], ['Japan', 883, 147, 'buyer'],
      ['South Korea', 849, 164, 'buyer'], ['Mexico', 191, 197, 'waste'], ['South Africa', 548, 337, 'waste'],
    ],
  },
  {
    id: 'muesli',
    name: 'Muesli',
    aliases: ['muesli', 'musli', 'müsli', 'cereal', 'breakfast cereal', 'cold cereal', 'oat cereal', 'oats cereal', 'mixed cereal', 'grain cereal', 'wholegrain cereal', 'whole grain cereal', 'muesli cereal', 'muesli mix', 'cereal mix', 'breakfast mix', 'oat mix', 'fruit and nut cereal', 'fruit cereal', 'nut cereal', 'granola', 'granola cereal', 'dry cereal', 'breakfast grains', 'rolled oat cereal'],
    category: 'Food',
    descriptor: 'Dry grain-based breakfast food',
    portable: true,
    powered: false,
    setting: 'breakfast and snack use',
    finishedPrice: {
      range: '$0.30–$2 per unit',
      basis: 'Typical retail equivalent for a 100 g dry serving: economy family packs at the low end and organic, high-nut or premium mixes at the high end.',
      tiers: [['Economy', '$0.30–$0.60'], ['Everyday', '$0.60–$1'], ['Organic', '$1–$1.50'], ['Premium nut mix', '$1.50–$2']],
    },
    guessMaterials: ['Rolled oats', 'Raisins', 'Wheat flakes', 'Almonds', 'Sunflower seeds'],
    materials: [
      ['Rolled oats', 60, 0.55], ['Raisins', 15, 2.80], ['Wheat flakes', 10, 0.45],
      ['Almonds', 5, 6.50], ['Sunflower seeds', 4, 1.60], ['Sugar or honey solids', 3, 1.10],
      ['Dried apple', 2, 5.00], ['Salt and minerals', 1, 0.25],
    ],
    stages: {
      sources: [['Canada', 14, null, ['Oats', 'wheat']], ['Russia', 12, null, ['Oats', 'wheat', 'sunflower seeds']], ['United States', 12, null, ['Almonds', 'oats', 'raisins']], ['Turkey', 10, null, ['Raisins', 'almonds']], ['Australia', 9, null, ['Oats', 'almonds', 'wheat']], ['Poland', 7, null, ['Oats', 'wheat', 'apples']], ['Finland', 6, null, ['Oats']], ['China', 6, null, ['Apples', 'raisins', 'wheat']], ['Ukraine', 5, null, ['Sunflower seeds', 'wheat']], ['Spain', 4, null, ['Almonds', 'raisins']], ['Chile', 3, null, ['Raisins', 'apples']], ['Argentina', 3, null, ['Sunflower seeds', 'wheat']], ['France', 2, null, ['Wheat', 'oats', 'apples']], ['Germany', 2, null, ['Oats', 'wheat', 'sugar']], ['Sweden', 1, null, ['Oats']], ['Other', 4, null, ['Honey', 'salt', 'minor fruits and nuts']]],
      assembly: [['United States', 16], ['Germany', 12], ['United Kingdom', 9], ['Switzerland', 8], ['France', 7], ['Australia', 6], ['Canada', 5], ['China', 5], ['Poland', 4], ['Netherlands', 4], ['Italy', 3], ['Spain', 3], ['Austria', 3], ['Sweden', 2], ['Finland', 2], ['Denmark', 2], ['New Zealand', 2], ['Japan', 1.5], ['South Korea', 1.5], ['South Africa', 1], ['Other', 3]],
      logistics: [['Netherlands', 13], ['Germany', 12], ['United States', 9], ['Belgium', 8], ['Singapore', 7], ['United Kingdom', 6], ['United Arab Emirates', 6], ['Canada', 5], ['Switzerland', 5], ['France', 4], ['Poland', 4], ['Australia', 3], ['Spain', 3], ['Hong Kong', 3], ['Turkey', 2], ['Panama', 2], ['South Africa', 2], ['Other', 6]],
      buyers: [['United States', 10], ['Germany', 8], ['United Kingdom', 7], ['France', 6], ['Canada', 5], ['Australia', 5], ['China', 5], ['Switzerland', 4], ['Netherlands', 4], ['Italy', 4], ['Spain', 4], ['Japan', 4], ['Poland', 3], ['Sweden', 3], ['Austria', 3], ['Belgium', 3], ['South Korea', 3], ['Denmark', 2.5], ['Finland', 2.5], ['New Zealand', 2], ['South Africa', 2], ['United Arab Emirates', 1.5], ['Singapore', 1.5], ['Brazil', 1.5], ['Mexico', 1.5], ['Other', 4]],
      waste: [['United States', 13.5], ['China', 9], ['Germany', 7], ['United Kingdom', 6], ['France', 5], ['Canada', 4.5], ['Australia', 4.5], ['Italy', 4], ['Spain', 4], ['Japan', 4], ['Netherlands', 3.5], ['Poland', 3.5], ['Russia', 3], ['Sweden', 3], ['South Korea', 3], ['Belgium', 2.5], ['Austria', 2.5], ['Brazil', 2.5], ['Mexico', 2.5], ['South Africa', 2], ['Finland', 2], ['New Zealand', 1.5], ['Indonesia', 1.5], ['United Arab Emirates', 1.5], ['Other', 4]],
    },
    feedback: [
      'It is a shelf-stable food usually portioned from a bag or box.',
      'Its largest ingredient consists of flattened whole grains rather than flour or dough.',
      'Dried fruit, nuts and seeds add smaller but more valuable shares of the mix.',
      'It is commonly eaten cold at breakfast, often with milk or yogurt.',
    ],
    mapRoles: {
      '124': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '643': ['source', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '792': ['source', 'logistics'], '036': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '616': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '246': ['source', 'assembly', 'buyer', 'waste'], '156': ['source', 'assembly', 'buyer', 'waste'], '804': ['source'],
      '724': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '152': ['source'], '032': ['source'],
      '250': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '752': ['source', 'assembly', 'buyer', 'waste'], '826': ['assembly', 'logistics', 'buyer', 'waste'],
      '756': ['assembly', 'logistics', 'buyer'], '528': ['assembly', 'logistics', 'buyer', 'waste'],
      '380': ['assembly', 'buyer', 'waste'], '040': ['assembly', 'buyer', 'waste'], '208': ['assembly', 'buyer'],
      '554': ['assembly', 'buyer', 'waste'], '392': ['assembly', 'buyer', 'waste'], '410': ['assembly', 'buyer', 'waste'],
      '710': ['assembly', 'logistics', 'buyer', 'waste'], '056': ['logistics', 'buyer', 'waste'],
      '702': ['logistics', 'buyer'], '784': ['logistics', 'buyer', 'waste'], '344': ['logistics'], '591': ['logistics'],
      '076': ['buyer', 'waste'], '484': ['buyer', 'waste'], '360': ['waste'],
    },
    mapLabels: [
      ['Canada', 214, 97, 'source'], ['Russia', 675, 85, 'source'], ['Turkey', 591, 142, 'source'],
      ['Germany', 528, 107, 'assembly'], ['United Kingdom', 493, 96, 'assembly'], ['Switzerland', 525, 124, 'assembly'],
      ['Netherlands', 514, 106, 'logistics'], ['Singapore', 789, 247, 'logistics'], ['Australia', 872, 319, 'buyer'],
      ['Japan', 883, 147, 'buyer'], ['Brazil', 356, 278, 'waste'], ['South Africa', 548, 337, 'waste'],
    ],
  },
  {
    id: 'cheese',
    name: 'Cheese',
    aliases: ['cheese', 'cheese block', 'block of cheese', 'piece of cheese', 'cheese wedge', 'wedge of cheese', 'cheese slice', 'sliced cheese', 'hard cheese', 'semi hard cheese', 'semi-hard cheese', 'aged cheese', 'mature cheese', 'dairy cheese', 'cow milk cheese', "cow's milk cheese", 'cheddar', 'cheddar cheese', 'gouda', 'gouda cheese', 'emmental', 'emmentaler', 'swiss cheese', 'edam', 'colby', 'monterey jack', 'jack cheese', 'gruyere', 'gruyère', 'tomme', 'queso'],
    category: 'Food',
    descriptor: 'Refrigerated everyday food',
    portable: true,
    powered: false,
    setting: 'meal and snack use',
    finishedPrice: {
      range: '$2–$12 per unit',
      basis: 'Typical retail range for a 250 g block: supermarket own-label at the low end and long-aged or specialty styles at the high end.',
      tiers: [['Value', '$2–$3.50'], ['Everyday', '$3.50–$6'], ['Aged', '$6–$9'], ['Specialty', '$9–$12']],
    },
    guessMaterials: ['Milk solids', 'Milk fat', 'Casein protein', 'Salt', 'Starter culture'],
    materials: [
      ['Retained water', 92.5, 0.002], ['Milk fat', 82.5, 6.50], ['Casein and other protein', 62.5, 8.00],
      ['Lactose and lactic acid', 4, 1.20], ['Salt', 4.5, 0.25], ['Calcium and minerals', 3.5, 1.50],
      ['Starter culture and rennet', 0.5, 35.00],
    ],
    stages: {
      sources: [['India', 17, null, ['Cow and buffalo milk', 'salt']], ['United States', 12, null, ['Cow milk', 'starter cultures']], ['Pakistan', 7, null, ['Buffalo and cow milk']], ['China', 7, null, ['Cow milk', 'salt']], ['Brazil', 6, null, ['Cow milk', 'salt']], ['Germany', 6, null, ['Cow milk', 'starter cultures']], ['France', 5, null, ['Cow milk', 'rennet']], ['New Zealand', 5, null, ['Cow milk', 'milk solids']], ['Russia', 5, null, ['Cow milk']], ['Turkey', 4, null, ['Cow and sheep milk', 'salt']], ['Netherlands', 4, null, ['Cow milk', 'starter cultures']], ['United Kingdom', 4, null, ['Cow milk', 'rennet']], ['Poland', 4, null, ['Cow milk']], ['Italy', 3, null, ['Cow milk', 'rennet']], ['Argentina', 3, null, ['Cow milk']], ['Australia', 2, null, ['Cow milk', 'milk solids']], ['Canada', 2, null, ['Cow milk', 'starter cultures']], ['Other', 4, null, ['Milk', 'salt', 'cultures and enzymes']]],
      assembly: [['United States', 19], ['Germany', 11], ['France', 9], ['Italy', 8], ['Netherlands', 6], ['Poland', 5], ['Russia', 5], ['United Kingdom', 4], ['Canada', 4], ['Argentina', 4], ['New Zealand', 4], ['Australia', 3], ['Turkey', 3], ['Brazil', 3], ['Spain', 2], ['Denmark', 2], ['Ireland', 2], ['Austria', 1], ['Switzerland', 1], ['Other', 4]],
      logistics: [['Netherlands', 13], ['Germany', 10], ['Belgium', 8], ['France', 7], ['United States', 7], ['New Zealand', 6], ['Denmark', 5], ['Ireland', 5], ['Italy', 5], ['Poland', 4], ['United Kingdom', 4], ['Singapore', 4], ['United Arab Emirates', 4], ['Australia', 3], ['Spain', 3], ['Canada', 3], ['Switzerland', 2], ['Turkey', 2], ['Panama', 2], ['Other', 3]],
      buyers: [['United States', 12], ['Germany', 8], ['France', 7], ['Italy', 6], ['United Kingdom', 6], ['Russia', 5], ['Canada', 5], ['Spain', 4], ['Netherlands', 4], ['Japan', 4], ['Belgium', 3], ['Australia', 3], ['Switzerland', 3], ['Poland', 3], ['Sweden', 3], ['Austria', 3], ['Denmark', 2.5], ['South Korea', 2.5], ['Mexico', 2], ['China', 2], ['Saudi Arabia', 2], ['United Arab Emirates', 2], ['Brazil', 1.5], ['New Zealand', 1.5], ['Turkey', 1], ['Other', 4]],
      waste: [['United States', 11], ['China', 8], ['Germany', 6], ['France', 5], ['United Kingdom', 6], ['Italy', 5], ['India', 5], ['Russia', 4], ['Canada', 4], ['Spain', 4], ['Brazil', 4], ['Japan', 4], ['Poland', 3.5], ['Netherlands', 3.5], ['Australia', 3], ['Mexico', 3], ['Turkey', 3], ['South Korea', 2.5], ['Belgium', 2.5], ['Sweden', 2], ['Austria', 2], ['South Africa', 2], ['Indonesia', 2], ['United Arab Emirates', 1], ['Other', 4]],
    },
    feedback: [
      'It is a perishable food that usually stays chilled until it is served.',
      'Most of its mass is concentrated milk fat, protein and retained water.',
      'Bacterial cultures and enzymes transform its starting liquid, sometimes followed by months of aging.',
      'It is commonly sold as a block, wedge or slice and paired with bread or crackers.',
    ],
    mapRoles: {
      '356': ['source', 'buyer', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '586': ['source'], '156': ['source', 'buyer', 'waste'], '076': ['source', 'assembly', 'buyer', 'waste'],
      '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '250': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '554': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '643': ['source', 'assembly', 'buyer', 'waste'],
      '792': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '528': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '826': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '616': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '380': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '032': ['source', 'assembly'],
      '036': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '124': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '724': ['assembly', 'logistics', 'buyer', 'waste'], '208': ['assembly', 'logistics', 'buyer'],
      '372': ['assembly', 'logistics'], '040': ['assembly', 'buyer', 'waste'], '756': ['assembly', 'logistics', 'buyer'],
      '056': ['logistics', 'buyer', 'waste'], '702': ['logistics'], '784': ['logistics', 'buyer', 'waste'],
      '591': ['logistics'], '392': ['buyer', 'waste'], '410': ['buyer', 'waste'], '752': ['buyer', 'waste'],
      '484': ['buyer', 'waste'], '682': ['buyer'], '710': ['waste'], '360': ['waste'],
    },
    mapLabels: [
      ['India', 719, 189, 'source'], ['United States', 222, 144, 'source'], ['Germany', 528, 107, 'assembly'],
      ['France', 509, 123, 'assembly'], ['Italy', 535, 130, 'assembly'], ['Netherlands', 514, 106, 'logistics'],
      ['Belgium', 510, 111, 'logistics'], ['New Zealand', 934, 371, 'logistics'], ['Japan', 883, 147, 'buyer'],
      ['Canada', 214, 97, 'buyer'], ['Brazil', 356, 278, 'waste'], ['South Africa', 548, 337, 'waste'],
    ],
  },
  {
    id: 'bread',
    name: 'Bread',
    aliases: ['bread', 'loaf', 'bread loaf', 'loaf of bread', 'sliced bread', 'sandwich bread', 'toast bread', 'toasting bread', 'wheat bread', 'wheat loaf', 'white bread', 'white loaf', 'brown bread', 'brown loaf', 'whole wheat bread', 'whole-wheat bread', 'wholemeal bread', 'wholemeal loaf', 'whole grain bread', 'wholegrain bread', 'multigrain bread', 'seeded bread', 'packaged bread', 'bakery bread', 'fresh bread', 'table bread', 'pan bread', 'pullman loaf', 'pain de mie', 'sandwich loaf', 'toast loaf'],
    category: 'Food',
    descriptor: 'Baked everyday food',
    portable: true,
    powered: false,
    setting: 'meal and snack use',
    finishedPrice: {
      range: '$1.50–$8 per unit',
      basis: 'Typical retail range for one packaged or bakery loaf: basic supermarket bread at the low end and artisan, seeded or specialty loaves at the high end.',
      tiers: [['Value', '$1.50–$2.50'], ['Everyday', '$2.50–$4'], ['Wholegrain / seeded', '$4–$6'], ['Artisan / specialty', '$6–$8']],
    },
    guessMaterials: ['Wheat flour', 'Water', 'Vegetable oil', 'Yeast', 'Salt'],
    materials: [
      ['Wheat flour solids', 270, 0.55], ['Retained water', 190, 0.002], ['Vegetable oil and fat', 15, 1.20],
      ['Sugar and malt solids', 10, 0.80], ['Salt', 6, 0.25], ['Yeast', 5, 3.00],
      ['Milk or soy solids', 2, 2.50], ['Enzymes and improvers', 1, 12.00], ['Preservatives', 1, 5.00],
    ],
    stages: {
      sources: [['China', 15, null, ['Wheat', 'soy oil']], ['India', 13, null, ['Wheat', 'sugar']], ['Russia', 12, null, ['Wheat', 'sunflower oil']], ['United States', 10, null, ['Wheat', 'soy oil', 'yeast']], ['France', 6, null, ['Wheat', 'yeast']], ['Canada', 6, null, ['Wheat', 'canola oil']], ['Australia', 5, null, ['Wheat', 'sugar']], ['Pakistan', 4, null, ['Wheat', 'sugar']], ['Germany', 4, null, ['Wheat', 'yeast']], ['Turkey', 3, null, ['Wheat', 'sunflower oil']], ['Ukraine', 3, null, ['Wheat', 'sunflower oil']], ['Argentina', 3, null, ['Wheat', 'soy oil']], ['Kazakhstan', 2, null, ['Wheat']], ['Brazil', 2, null, ['Sugar', 'soy oil']], ['Romania', 2, null, ['Wheat', 'sunflower oil']], ['Poland', 2, null, ['Wheat', 'yeast']], ['United Kingdom', 2, null, ['Wheat', 'malt']], ['Mexico', 2, null, ['Wheat', 'sugar']], ['Other', 4, null, ['Salt', 'enzymes', 'milk solids and preservatives']]],
      assembly: [['China', 16], ['United States', 12], ['India', 10], ['Brazil', 6], ['Germany', 6], ['Russia', 6], ['United Kingdom', 5], ['France', 5], ['Turkey', 4], ['Mexico', 4], ['Japan', 4], ['Indonesia', 3], ['Pakistan', 3], ['Italy', 3], ['Spain', 2], ['Canada', 2], ['Australia', 2], ['Poland', 2], ['South Africa', 1], ['Other', 4]],
      logistics: [['Netherlands', 12], ['Germany', 10], ['Belgium', 8], ['United States', 8], ['Singapore', 7], ['United Arab Emirates', 7], ['France', 6], ['Turkey', 5], ['United Kingdom', 5], ['Mexico', 5], ['Poland', 4], ['Canada', 4], ['Spain', 4], ['Malaysia', 3], ['Panama', 3], ['Australia', 2], ['South Africa', 2], ['Italy', 1], ['Other', 4]],
      buyers: [['China', 12], ['United States', 10], ['India', 8], ['Germany', 6], ['United Kingdom', 4], ['France', 5], ['Brazil', 5], ['Russia', 4], ['Mexico', 4], ['Japan', 4], ['Turkey', 3.5], ['Italy', 3.5], ['Spain', 3], ['Indonesia', 3], ['Pakistan', 3], ['Canada', 2.5], ['Poland', 2.5], ['Australia', 2.5], ['South Africa', 2], ['Nigeria', 2], ['Saudi Arabia', 2], ['United Arab Emirates', 1.5], ['Philippines', 1.5], ['Argentina', 1.5], ['Other', 4]],
      waste: [['China', 13], ['United States', 10], ['India', 7], ['Germany', 5], ['United Kingdom', 5], ['France', 5], ['Brazil', 5], ['Russia', 4], ['Indonesia', 4], ['Mexico', 4], ['Japan', 4], ['Turkey', 3.5], ['Italy', 3.5], ['Spain', 3], ['Pakistan', 3], ['Nigeria', 3], ['Canada', 2.5], ['Poland', 2.5], ['Australia', 2.5], ['South Africa', 2], ['Philippines', 2], ['Argentina', 1.5], ['United Arab Emirates', 1], ['Other', 4]],
    },
    feedback: [
      'It is a short-lived food that is often bought several times a week.',
      'Wheat flour and retained water account for most of its finished mass.',
      'Yeast creates gas inside a dough before heat fixes its porous structure.',
      'It is commonly sold as a sliced loaf and used for toast or sandwiches.',
    ],
    mapRoles: {
      '156': ['source', 'assembly', 'buyer', 'waste'], '356': ['source', 'assembly', 'buyer', 'waste'],
      '643': ['source', 'assembly', 'buyer', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '250': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '124': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '036': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '586': ['source', 'assembly', 'buyer', 'waste'],
      '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '792': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '804': ['source'], '032': ['source', 'buyer', 'waste'], '398': ['source'], '076': ['source', 'assembly', 'buyer', 'waste'],
      '642': ['source'], '616': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '826': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '484': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '392': ['assembly', 'buyer', 'waste'],
      '360': ['assembly', 'buyer', 'waste'], '380': ['assembly', 'logistics', 'buyer', 'waste'],
      '724': ['assembly', 'logistics', 'buyer', 'waste'], '710': ['assembly', 'logistics', 'buyer', 'waste'],
      '528': ['logistics'], '056': ['logistics'], '702': ['logistics'], '784': ['logistics', 'buyer', 'waste'],
      '458': ['logistics'], '591': ['logistics'], '410': ['buyer', 'waste'], '566': ['buyer', 'waste'],
      '682': ['buyer'], '608': ['buyer', 'waste'],
    },
    mapLabels: [
      ['China', 789, 153, 'source'], ['India', 719, 189, 'source'], ['Russia', 675, 85, 'source'],
      ['United States', 222, 144, 'assembly'], ['Germany', 528, 107, 'assembly'], ['Brazil', 356, 278, 'assembly'],
      ['Netherlands', 514, 106, 'logistics'], ['Singapore', 789, 247, 'logistics'], ['Mexico', 191, 197, 'buyer'],
      ['Japan', 883, 147, 'buyer'], ['Nigeria', 500, 250, 'waste'], ['South Africa', 548, 337, 'waste'],
    ],
  },
  {
    id: 'toothpaste',
    name: 'Toothpaste',
    aliases: ['toothpaste', 'tooth paste', 'dental paste', 'dentifrice', 'tooth gel', 'dental gel', 'oral care paste', 'oral-care paste', 'oral hygiene paste', 'fluoride toothpaste', 'fluoride paste', 'fluoridated toothpaste', 'mint toothpaste', 'whitening toothpaste', 'sensitive toothpaste', 'sensitivity toothpaste', 'anti cavity toothpaste', 'anticavity toothpaste', 'anti-cavity toothpaste', 'cavity protection toothpaste', 'tartar control toothpaste', 'gum care toothpaste', 'childrens toothpaste', "children's toothpaste", 'kids toothpaste', "kids' toothpaste", 'adult toothpaste', 'tooth cleaning paste', 'tooth cleaner', 'paste for teeth', 'tube of toothpaste', 'toothpaste tube', 'dental cream', 'tooth cream'],
    category: 'Personal care',
    descriptor: 'Daily personal-care product',
    portable: true,
    powered: false,
    setting: 'oral hygiene use',
    finishedPrice: {
      range: '$1–$15 per unit',
      basis: 'Typical retail equivalent for a roughly 100 g packaged tube: value formulas at the low end and specialty sensitivity, whitening or premium products at the high end.',
      tiers: [['Value', '$1–$3'], ['Everyday fluoride', '$3–$6'], ['Specialty', '$6–$10'], ['Premium', '$10–$15']],
    },
    guessMaterials: ['Hydrated silica', 'Sorbitol', 'Glycerin', 'Fluoride compound', 'Tube laminate'],
    materials: [
      ['Hydrated silica or calcium carbonate', 35, 0.45], ['Sorbitol and glycerin', 25, 1.10], ['Water', 20.24, 0.002],
      ['Aluminum–polyethylene tube laminate', 12, 3.20], ['Polypropylene cap', 2.76, 1.20],
      ['Cellulose gums and thickeners', 1.5, 4.00], ['Surfactants', 1.5, 2.20],
      ['Flavor oils and sweeteners', 1, 18.00], ['Preservatives and colorants', 0.76, 8.00],
      ['Fluoride compound', 0.24, 4.50],
    ],
    stages: {
      sources: [['China', 18, null, ['Silica', 'fluoride minerals', 'aluminum', 'glycerin']], ['United States', 10, null, ['Soda ash', 'silica', 'sorbitol']], ['India', 9, null, ['Calcium carbonate', 'glycerin', 'mint oil']], ['Brazil', 7, null, ['Sorbitol feedstock', 'glycerin']], ['Indonesia', 6, null, ['Glycerin', 'surfactant feedstocks']], ['Germany', 6, null, ['Cellulose gums', 'surfactants']], ['France', 5, null, ['Flavor oils', 'thickeners']], ['Thailand', 5, null, ['Glycerin', 'surfactant feedstocks']], ['Malaysia', 5, null, ['Glycerin', 'polyethylene feedstocks']], ['Australia', 4, null, ['Silica', 'fluoride minerals']], ['Mexico', 4, null, ['Fluorspar', 'calcium carbonate']], ['South Africa', 4, null, ['Fluorspar', 'silica']], ['Turkey', 3, null, ['Calcium carbonate', 'soda ash']], ['Morocco', 3, null, ['Phosphate rock', 'fluoride minerals']], ['Canada', 3, null, ['Aluminum', 'cellulose']], ['Spain', 2, null, ['Calcium carbonate', 'flavor oils']], ['Vietnam', 2, null, ['Glycerin', 'mint oil']], ['Other', 4, null, ['Sweeteners', 'preservatives', 'pigments and polymers']]],
      components: [
        ['China', 22, null, ['Laminated tubes', 'caps', 'precipitated silica'], '156'],
        ['United States', 14, null, ['Fluoride compounds', 'flavours', 'tubes'], '840'],
        ['India', 10, null, ['Calcium carbonate', 'tubes', 'flavours'], '356'],
        ['Germany', 8, null, ['Silica abrasives', 'tubes', 'flavours'], '276'],
        ['Mexico', 7, null, ['Tubes', 'caps', 'cartons'], '484'],
        ['Poland', 6, null, ['Tubes', 'caps', 'cartons'], '616'],
        ['Brazil', 6, null, ['Calcium carbonate', 'tubes'], '076'],
        ['France', 5, null, ['Flavours', 'tubes', 'cartons'], '250'],
        ['Thailand', 5, null, ['Tubes', 'caps'], '764'],
        ['Indonesia', 4, null, ['Sorbitol', 'tubes'], '360'],
        ['Turkey', 3, null, ['Calcium carbonate', 'cartons'], '792'],
        ['South Korea', 3, null, ['Silica', 'laminated tubes'], '410'],
        ['Other', 7, null, ['Minor formula inputs', 'liners', 'closures'], null],
      ],
      assembly: [['China', 26], ['United States', 12], ['India', 9], ['Germany', 7], ['Mexico', 6], ['Poland', 5], ['Brazil', 5], ['United Kingdom', 4], ['Thailand', 4], ['Indonesia', 3], ['Turkey', 3], ['France', 3], ['Italy', 2], ['Spain', 2], ['Japan', 2], ['South Korea', 2], ['South Africa', 1], ['Egypt', 1], ['Other', 3]],
      logistics: [['Netherlands', 12], ['Germany', 11], ['Singapore', 9], ['United Arab Emirates', 8], ['Belgium', 8], ['United States', 7], ['Hong Kong', 7], ['Mexico', 6], ['Poland', 5], ['Turkey', 4], ['Malaysia', 4], ['United Kingdom', 4], ['Panama', 3], ['Spain', 3], ['France', 3], ['South Africa', 2], ['Canada', 1], ['Other', 3]],
      buyers: [['United States', 13], ['China', 9], ['India', 7.5], ['Germany', 6], ['United Kingdom', 5], ['Brazil', 5], ['Japan', 4], ['France', 4], ['Mexico', 4], ['Indonesia', 3.5], ['Italy', 3.5], ['Spain', 3], ['Canada', 3], ['Russia', 3], ['Turkey', 3], ['South Korea', 2.5], ['Poland', 2.5], ['Australia', 2.5], ['Nigeria', 2], ['South Africa', 2], ['Saudi Arabia', 2], ['Thailand', 2], ['Philippines', 1.5], ['United Arab Emirates', 1.5], ['Argentina', 1], ['Other', 4]],
      waste: [['China', 12], ['United States', 10], ['India', 8], ['Brazil', 5], ['Indonesia', 5], ['Germany', 5], ['Mexico', 4], ['Japan', 4], ['Russia', 4], ['United Kingdom', 4], ['France', 4], ['Turkey', 3.5], ['Italy', 3.5], ['Nigeria', 3], ['Spain', 3], ['Pakistan', 3], ['South Korea', 2.5], ['Poland', 2.5], ['Thailand', 2], ['Philippines', 2], ['South Africa', 2], ['Canada', 1.5], ['Australia', 1.5], ['United Arab Emirates', 1], ['Other', 4]],
    },
    feedback: [
      'It is a small consumable personal-care product usually kept in a bathroom.',
      'Abrasive minerals and moisture-holding liquids make up most of what is inside its package.',
      'A regulated fluoride compound may appear in a fraction of one gram, alongside flavor and surfactant.',
      'A small amount is squeezed from a tube onto a brush during a daily cleaning routine.',
    ],
    mapRoles: {
      '156': ['source', 'assembly', 'buyer', 'waste'], '840': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '356': ['source', 'assembly', 'buyer', 'waste'], '076': ['source', 'assembly', 'buyer', 'waste'],
      '360': ['source', 'assembly', 'buyer', 'waste'], '276': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '250': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '764': ['source', 'assembly', 'buyer', 'waste'],
      '458': ['source', 'logistics'], '036': ['source', 'buyer', 'waste'], '484': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '710': ['source', 'assembly', 'logistics', 'buyer', 'waste'], '792': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '504': ['source'], '124': ['source', 'logistics', 'buyer', 'waste'], '724': ['source', 'assembly', 'logistics', 'buyer', 'waste'],
      '704': ['source'], '616': ['assembly', 'logistics', 'buyer', 'waste'], '826': ['assembly', 'logistics', 'buyer', 'waste'],
      '380': ['assembly', 'buyer', 'waste'], '392': ['assembly', 'buyer', 'waste'], '410': ['assembly', 'buyer', 'waste'],
      '818': ['assembly'], '528': ['logistics'], '702': ['logistics'], '784': ['logistics', 'buyer', 'waste'],
      '056': ['logistics'], '344': ['logistics'], '591': ['logistics'], '643': ['buyer', 'waste'],
      '566': ['buyer', 'waste'], '682': ['buyer'], '608': ['buyer', 'waste'], '586': ['waste'],
    },
    mapLabels: [
      ['China', 789, 153, 'source'], ['United States', 222, 144, 'source'], ['India', 719, 189, 'source'],
      ['Germany', 528, 107, 'assembly'], ['Mexico', 191, 197, 'assembly'], ['Poland', 553, 101, 'assembly'],
      ['Netherlands', 514, 106, 'logistics'], ['Singapore', 789, 247, 'logistics'], ['Brazil', 356, 278, 'buyer'],
      ['Japan', 883, 147, 'buyer'], ['Nigeria', 500, 250, 'waste'], ['South Africa', 548, 337, 'waste'],
    ],
  },
]
